### ISSUE TITLE
Initial Plan

### ISSUE THREAD

**Issue by phillipleblanc** [datafusion-contrib/datafusion-table-providers#1]
This repo was created in response to this discussion on the main DataFusion repo: https://github.com/apache/datafusion/discussions/9963#discussioncomment-9145886

The plan is to start moving over TableProviders from https://github.com/spiceai/spiceai/tree/trunk/crates/data_components to jump start this repo, starting with `PostgreSQL`, `SQLite`, `MySQL` and `DuckDB` TableProviders.

However, there are several known bugs with them in their current state that prevent them from working well, and we are actively improving them. Most of the bugs are around handling of data types correctly.

Once they have stabilized a bit more (expect in the next few weeks), then I think it makes sense to start bringing them over here, and changing our project to reference the TableProviders in this repo.

**Comment by matthewmturner** [comment]
As an FYI I am working on a web socket table provider (it works right now, but is very limited) that i plan to contribute here

**Comment by c-thiel** [comment]
@phillipleblanc , are you still working on this?
We also need Postgres and a few other connectors and are currently thinking about a good way to approach this.

**Comment by phillipleblanc** [comment]
@c-thiel Yes! Apologies for the delay - but I think we're getting close to being able to move some connectors over (still targeting the 4 I mentioned above: `PostgreSQL`, `SQLite`, `MySQL` and `DuckDB`). 

There are 2 main blockers I'm working on now:
1) There is one dependency in https://github.com/spiceai/spiceai/tree/trunk/crates/data_components that doesn't make sense to move over to this repo (it's specific to our scenario), so I will work on moving that out. 
2) We also heavily invested in making these TableProviders work well with https://github.com/datafusion-contrib/datafusion-federation - and we have a queue of changes in our [fork](https://github.com/datafusion-contrib/datafusion-federation/compare/main...spiceai:datafusion-federation:spiceai) that I need to contribute back to the upstream repo first.

**Comment by backkem** [comment]
Happy to help review the federation changes.

**Comment by c-thiel** [comment]
@phillipleblanc thanks for coming back. We have a few proposals for changes in the SpiceAI connector before bringing it over here - among them is using "COPY OUT" instead of "SELCT" for better performance. We (me and [@twuebi](http://github.com/twuebi)) could contribute those as well. We were thinking about starting our own repo, but I think joining forces here could be great.
I pinged you on LinkedIn. Maybe we can have a quick chat to understand your constraints and also figure out if a collaboration makes sense?

**Comment by phillipleblanc** [comment]
Update: I've begun the process of moving over the code. My WIP branch is here: https://github.com/datafusion-contrib/datafusion-table-providers/tree/phillip/240630-initial-providers

**Comment by phillipleblanc** [comment]
I've merged #2 which adds support for the initial providers for DuckDB, PostgreSQL, Sqlite and MySQL.

There is still a lot of work to be done - need to set up CI, remove dependencies on our forks, and publish to crates.io. But this is a start!

**Comment by phillipleblanc** [comment]
I've set up basic CI and #11 removed the Spice AI datafusion fork and now references DataFusion 40 directly. `datafusion-federation` now also references the crates.io version. However because `datafusion-federation-sql` isn't published on crates.io yet, that is still referencing the Spice AI fork for now.

**Comment by phillipleblanc** [comment]
Closing this as the initial release on crates is published: https://crates.io/crates/datafusion-table-providers
