### ISSUE TITLE
use datafusion `plan_to_sql` function instead of `expr_to_sql`

### ISSUE THREAD

**Issue by hozan23** [datafusion-contrib/datafusion-table-providers#103]
Hello,

Following on #18, #99 and #102, we are thinking to use the [`plan_to_sql`](https://docs.rs/datafusion/latest/datafusion/sql/unparser/fn.plan_to_sql.html) function within the `SqlTable.scan()` implementation, instead of generating the SQL query using the [`sql()`](https://github.com/datafusion-contrib/datafusion-table-providers/blob/main/src/sql/sql_provider_datafusion/mod.rs#L272) function from `SqlExec`.

The proposed approach is:
- From the `scan()` function -> create a new logical plan -> pass it to the `plan_to_sql` function -> pass the generated SQL string to `SqlExec`.

One concern with this approach is that we may lose the ability to implement custom logic for each engine. A possible solution would be to use the [`CustomDialect`](https://docs.rs/datafusion/latest/datafusion/sql/unparser/dialect/struct.CustomDialectBuilder.html) for engines that don't have supported dialects in DataFusion.

cc: @phillipleblanc, @backkem

**Comment by phillipleblanc** [comment]
This makes sense to me.

**Comment by hozan23** [comment]
Resolved with #106
