### ISSUE TITLE
Query postgres information_schema to construct datafusion table schema

### ISSUE THREAD

**Issue by derekleverenz** [datafusion-contrib/datafusion-table-providers#127]
Trying to query an emtpy table results in a schema error, and I noticed that an empty table in postgres did not have any schema when mapped via a TableProvider, and after some digging saw that the schema is determined via a `SELECT * FROM {table} LIMIT 1` in https://github.com/datafusion-contrib/datafusion-table-providers/blob/5bbbb32704ad8bfd534c7fa9b6651df03c0ff6bd/src/sql/db_connection_pool/dbconnection/postgresconn.rs#L85  so no data means no schema. 

A potential improvement that would allow querying empty tables is to build the schema by querying postgres's information_schema and mapping it to arrow/df schema. 

I didn't look into other implementations to determine if other databases share this issue.

**Comment by phillipleblanc** [comment]
I have a PR that implements this: https://github.com/datafusion-contrib/datafusion-table-providers/pull/153
