### ISSUE TITLE
Any plans to support a DB CatalogProvider?

### ISSUE THREAD

**Issue by holicc** [datafusion-contrib/datafusion-table-providers#172]
For now, this crate only supports `TableProvider`, which means every time we want to use a new external database table, we have to modify the code and register the new table with Datafusion. So, I think we should add a more general implementation as `CatalogProvider`.

For example, if we want to select multiple tables from PostgreSQL:

```rust
let ctx = Session::new();
let pg_catalog = PostgresqlCatalogProvider::new();
ctx.regiter_catalog(pg_catalog);

ctx.sql("select * from users");
ctx.sql("select * from commits");
```

**Comment by phillipleblanc** [comment]
We don't have any plans at the moment to implement this. I do expect the Catalog/Schema providers should be relatively straightforward to implement on top of the existing table provider implementations, if anyone wanted to contribute a PR for it.

**Comment by holicc** [comment]
I am happy to implement this PR. Please let me know any specific details or requirements, and I'll get started as soon as possible.

**Comment by phillipleblanc** [comment]
You could start by implementing the Postgres catalog provider as a submodule here `src/postgres/catalog.rs` then update the examples to show how to use it.

**Comment by holicc** [comment]
> You could start by implementing the Postgres catalog provider as a submodule here `src/postgres/catalog.rs` then update the examples to show how to use it.

Should we make a more general implementation instead of a specific one for every database?

**Comment by phillipleblanc** [comment]
I'm not sure that they would be generalizable across database providers. If they can, then I think we still have specific implementations that all referenced a common library implementation. This is similar to how the table providers in this repo delegate to https://github.com/datafusion-contrib/datafusion-table-providers/blob/main/src/sql/sql_provider_datafusion/mod.rs#L86 for the common TableProvider trait logic.

However, I'm not convinced that our decision to structure it like that actually saved that much work in the end.

**Comment by holicc** [comment]
> I'm not sure that they would be generalizable across database providers. If they can, then I think we still have specific implementations that all referenced a common library implementation. This is similar to how the table providers in this repo delegate to https://github.com/datafusion-contrib/datafusion-table-providers/blob/main/src/sql/sql_provider_datafusion/mod.rs#L86 for the common TableProvider trait logic.
> 
> However, I'm not convinced that our decision to structure it like that actually saved that much work in the end.

I've completed the first version, #175. Please let me know if any changes are needed. Thanks. :)
