### ISSUE TITLE
Use DataFusion unparser instead of sql_provider_datafusion/expr.rs

### ISSUE THREAD

**Issue by phillipleblanc** [datafusion-contrib/datafusion-table-providers#18]
There is basic support for converting DataFusion `expr` to SQL as part of https://github.com/datafusion-contrib/datafusion-table-providers/blob/main/src/sql/sql_provider_datafusion/expr.rs

We should just be using the [DataFusion unparser](https://github.com/apache/datafusion/blob/main/datafusion/sql/src/unparser/expr.rs#L105) directly and remove this crate's version.

**Comment by hozan23** [comment]
@phillipleblanc I think we can close this issue ref: #99, #102
