### ISSUE TITLE
mysql: error when converting timestamp(3) to ColumnType

### ISSUE THREAD

**Issue by hozan23** [datafusion-contrib/datafusion-table-providers#94]
Hello,

The error coming from [this function](https://github.com/hozan23/datafusion-table-providers/blob/main/src/sql/db_connection_pool/dbconnection/mysqlconn.rs#L191 )

I fixed it with a [dump patch](https://github.com/hozan23/datafusion-table-providers/commit/7510dd95d87a7c61f615f66eff9abde84284cb58?diff=unified&w=0)  but i don't think that's the ideal way to fix it.

**Comment by Sevenannn** [comment]
Hi @hozan23 , thanks for spotting the issue and contributing!

We found that there are more places to fix apart from the dump patch you provided, so implemented the full change in this PR [Correctly handle mysql timestamp() and datetime() types](https://github.com/datafusion-contrib/datafusion-table-providers/pull/96). This will support all `timestamp()` and `datetime()` mysql type, including the `timestamp(3)` you are having problem with. We’d love your review and feedback on the change. Thanks!

**Comment by hozan23** [comment]
I will close this issue, thanks @Sevenannn for the fix #96.
